### PR TITLE
PeerCount method + PublicRPCService

### LINKED ISSUE #52: Implement RPC Services

### PR DESCRIPTION
**Pull request by dutterbutter**
This PR introduces the first RPC service and method attached. Currently, I cannot test the PeerCount method that would be invoked by the `PublicRPC` service because I would need a simulated P2P running which we don't have yet, see #53. I did, however, test the `PeerCount()` function within the P2P package itself to ensure the actual function works, and since there is test coverage for registering RPC services this might be sufficient. 

## Changes
- Added `PeerCount() int` function
- Added `PublicRPC` service that will be registered and used to invoke `PeerCount()` and `NewPublicRPC`

## Tests:
```
go test ./p2p -run TestService_PeerCount
```

### Fixes: Closes #52

### CODE REVIEW

**Comment by noot** [comment]
I am getting some sort of dependency issue:
```
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.0()
	/home/elizabeth/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.1/internal/handshake/unsafe.go:20 +0x113
FAIL	github.com/ChainSafe/gossamer/p2p	0.009s
```

did we remove quic-go from go.mod at some point? I believe we need version 0.10.0

**Comment by dutterbutter** [comment]
> I am getting some sort of dependency issue:
> 
> ```
> panic: qtls.ClientSessionState not compatible with tls.ClientSessionState
> 
> goroutine 1 [running]:
> github.com/lucas-clemente/quic-go/internal/handshake.init.0()
> 	/home/elizabeth/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.1/internal/handshake/unsafe.go:20 +0x113
> FAIL	github.com/ChainSafe/gossamer/p2p	0.009s
> ```
> 
> did we remove quic-go from go.mod at some point? I believe we need version 0.10.0

I am not getting that same dependency issue, please delete your go mod/go sum and vendor dir and run the test again.

If the issue persists, we may need to lock down quic-go to version 0.10.0.

**Comment by noot** [comment]
@dutterbutter can you update go.mod to include quic-go at version 0.10.0? still having issues

it looks like its due to another package now...

```
# github.com/libp2p/go-libp2p-connmgr
../../../../pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.0.1/connmgr.go:40:5: cannot use (*BasicConnMgr)(nil) (type *BasicConnMgr) as type ifconnmgr.ConnManager in assignment:
```

**Comment by ansermino** [comment]
Would it not make sense to separate things such as networking into their own services instead of having a meta-service? This would make turning them on/off quite easy

**Comment by dutterbutter** [comment]
> @dutterbutter can you update go.mod to include quic-go at version 0.10.0? still having issues
> 
> it looks like its due to another package now...
> 
> ```
> # github.com/libp2p/go-libp2p-connmgr
> ../../../../pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.0.1/connmgr.go:40:5: cannot use (*BasicConnMgr)(nil) (type *BasicConnMgr) as type ifconnmgr.ConnManager in assignment:
> ```

I will look into this but I am not experiencing the same issue.

**Comment by dutterbutter** [comment]
> Would it not make sense to separate things such as networking into their own services instead of having a meta-service? This would make turning them on/off quite easy

That's a good point !

**Comment by noot** [comment]
@dutterbutter can you update go.mod to include quic-go at version 0.10.0? still having issues

**Comment by dutterbutter** [comment]
@noot I looked into downgrading `quic-go to v0.10.0` however since its a dependency of `go-ipfs and go-libp2p` it caused those gx issues to reappear.
```
package github.com/ChainSafe/gossamer/p2p (test)
	imports github.com/ipfs/go-ipfs/core
	imports gx/ipfs/QmNohiVssaPw3KVLZik59DBVGTSm2dGvYT9eoXt5DQ36Yz/go-ipfs-util: unknown import path "gx/ipfs/QmNohiVssaPw3KVLZik59DBVGTSm2dGvYT9eoXt5DQ36Yz/go-ipfs-util": cannot find module providing package gx/ipfs/QmNohiVssaPw3KVLZik59DBVGTSm2dGvYT9eoXt5DQ36Yz/go-ipfs-util
FAIL	github.com/ChainSafe/gossamer/p2p [setup failed]
```
 Again, I have no dependency issue while running the tests but we can discuss tomorrow. Make sure to `go clean` and delete `go mod`, `go sum`, and `vendor/` to remove possible old cache, etc. Also if David is experiencing the same issue I will dig deeper into the problem.

**Comment by dutterbutter** [comment]
> Probably makes sense to add the ability to actually get the peers (ie. return the list of peers not just the length of the list). Please include here or open an issue.

I was thinking that would be separate call (eg. peerInfo), thoughts?

**Comment by noot** [comment]
@dutterbutter I think that should be a separate function, its actually a bit more complicated to get the actual list of connected peers I believe. lets open an issue

**Pull request merged**
