### PR TITLE
Added Parachain Protocol to Gossamer docs

### PR DESCRIPTION
**Pull request by kishansagathiya**
## Changes

Added docs for 
- Parachain Protocol Overview 
- Candidate backing.
- Availability Subsystems 

(This PR basically moves things from https://github.com/kishansagathiya/parachain-protocol/ to gossamer docs)
(@edwardmack have converted from your PPT to Markdown here, let me know if it is as expected.)
## Tests

```
cd docs
mkdocs serve
```

You will need to separately install the material theme (https://github.com/squidfunk/mkdocs-material)
```
pip install mkdocs-material
```

On macbook, I had to remove existing mkdocs installation and install mkdocs-material
```
pipx install mkdocs-material --include-deps --force
```

### CODE REVIEW

**Comment by haikoschol** [comment]
@kishansagathiya Should this be merged to `development`? I set #4346 to be merged to `feat/parachain`.

**Review by haikoschol — APPROVED** [review]

**Comment by kishansagathiya** [comment]
@haikoschol 
The goal of writing docs in this way is for them to show up over here https://gossamer.chainsafe.io/, that would happen only if we put them in development. 

Checkout the github workflow over here using which this gets deployed, https://github.com/ChainSafe/gossamer/blob/a568da62a2bb7c69f41c17aeb88738d501c7a720/.github/workflows/docs.yml#L5

**Comment by haikoschol** [comment]
> @haikoschol The goal of writing docs in this way is for them to show up over here https://gossamer.chainsafe.io/, that would happen only if we put them in development.

Should I change my PR to merge to `development` as well then?

**Comment by kishansagathiya** [comment]
> Should I change my PR to merge to development as well then?

@haikoschol yes

**Review by P1sar — APPROVED** [review]

**Review by P1sar — CHANGES_REQUESTED** [review]
the folder name should be design (not designs)

**Review by edwardmack — APPROVED** [review]

**Review by P1sar — APPROVED** [review]

**Pull request merged**
