### PR TITLE
enhancement(network): Change log level of banned threshold error

### PR DESCRIPTION
**Pull request by jimjbrettj**
## Changes

- After investigating this log to see what the problem was, it does not seem to cause any problems that affect the node's behavior, so I change the log level from critical to debug

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Primary Reviewer

@axaysagathiya

### CODE REVIEW

**Review by kishansagathiya — CHANGES_REQUESTED** [review]
I have found this log quite useful while running gossamer network. When reputation is less than banned threshold, we remove that peer. If highest rated peer is below banned threshold, no one is connected to us. I would consider that as an important log to put as critical.

**Comment by dimartiro** [comment]
> I have found this log quite useful while running gossamer network. When reputation is less than banned threshold, we remove that peer. If highest rated peer is below banned threshold, no one is connected to us. I would consider that as an important log to put as critical.

we can maybe add a `Critical` log for that case only, if no one is connected to us, and keep this as `Debug`

**Comment by kishansagathiya** [comment]
> we can maybe add a Critical log for that case only, if no one is connected to us, and keep this as Debug

Seeing this message means we don't know any peers with enough reputation to be connected to us.

**Comment by jimjbrettj** [comment]
@kishansagathiya it seems that we are hitting this case while we still do have peers connected, thus this does not seem critical to me. I think that critical logs should be reserved for cases where the node should shut down, and in this case, the node runs as I expect it to even with this error. I also do not see where we are removing the peer causing us to hit this case.

From my POV, I am getting spammed with a log that is not impacting the function of the node which feels not ideal. However, given the points you made above, I will do a little more investigating and see if I can modify how often this case gets hit, and perhaps change to error log instead. Will update this PR with my findings

**Comment by jimjbrettj** [comment]
This PR does not fix the lower-level issue of why the log is occurring. Changing the log level therefore is not the best approach and thus I will continue to investigate the underlying issue here. I will close this PR since it is not needed and either open a new PR with the fix or create an issue to represent the results of my investigation.

**Pull request closed without merging**
