### PR TITLE
feat(infra): Use shared disk as state snapshot in staging instances

### PR DESCRIPTION
**Pull request by dimartiro**
## Changes

Use AWS EFS disks to store blocks state and share it between nodes for the same chain.
This EFS disks are configure to create backups daily acting as daily chain snapshots

Would be great if we update chainDB to use badgerV4 before merging this PR

## Tests

Tested on AWS

## Issues

#3252 

## Primary Reviewer

@timwu20

### CODE REVIEW

**Review by EclesioMeloJunior — APPROVED** [review]

**Review by jimjbrettj — APPROVED** [review]
lgtm

**Comment by dimartiro** [comment]
@timwu20 are we going to hold this PR until create new nodes starting from genesis?

**Comment by q9f** [comment]
this is not a `feat(sync)` but a `chore(ci)` since it does not touch any gossamer code.

@timwu20, any update on this?

**Comment by timwu20** [comment]
I think we should run more staging nodes that start from the latest stored state, and we should have ones that start from genesis.

**Comment by timwu20** [comment]
I created an issue to track the new infra setup to run a suite of nodes from shared state (latest sync'd block) and from genesis #3696

**Comment by P1sar** [comment]
@dimartiro what is the status of this PR? Could you please add more details why it is blocked and how are we tracking unblocking progress? 
cc @timwu20

**Comment by dimartiro** [comment]
> @dimartiro what is the status of this PR? Could you please add more details why it is blocked and how are we tracking unblocking progress? cc @timwu20

Sure! basically because of [this](https://github.com/ChainSafe/gossamer/pull/3251#issuecomment-1893930240) we have an [issue](https://github.com/ChainSafe/gossamer/issues/3696) to create the pending infra to run some set of nodes from genesis and another set using this change resuming from the snapshot every time they are restarted.
We are waiting for that to merge & deploy this PR

**Comment by dimartiro** [comment]
I think we can close this now based on our latest infra changes right? @timwu20 @P1sar

**Pull request closed without merging**
