### PR TITLE
chore: change tests log level to info

### LINKED ISSUE #1616: Set logger to Info level in unit test.
## Issue summary

- Set logger to `Info` level in the unit test.
- Couple of tests set the log levels to `trace` and `debug` and this slows the test execution.

## Other information and links

-

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- Change the unit tests log level from `debug` or `trace` to info 

## Tests

N/A

## Issues

- closes #1616

### CODE REVIEW

**Comment by noot** [comment]
@EclesioMeloJunior I think the issue was to set the log levels to info for services that are created in tests, for example by setting the `Config.LogLevel` to `LvlInfo`, this PR shouldn't change any existing log levels

**Comment by arijitAD** [comment]
> @EclesioMeloJunior I think the issue was to set the log levels to info for services that are created in tests, for example by setting the `Config.LogLevel` to `LvlInfo`, this PR shouldn't change any existing logging. correct me if I'm wrong @arijitAD

Yes. When creating service in the test we should set the log level to info instead of trace/debug.
https://github.com/ChainSafe/gossamer/blob/304d8ac542d14c1556c9cf5baf6ac5c5fff92e85/dot/state/service_test.go#L51

**Comment by EclesioMeloJunior** [comment]
@arijitAD @noot fixed!

**Review by arijitAD — APPROVED** [review]
Look good! Can you run `go mod tidy`?

**Review by noot — APPROVED** [review]

**Pull request merged**
