### PR TITLE
chore(chain): add telemetry and bootnodes

### PR DESCRIPTION
**Pull request by q9f**
## Changes

Applied all proposed upstream changes for better peering: https://github.com/paseo-network/runtimes/pulls

Also added Telemetry so we can monitor our nodes.

## Primary Reviewer

@EclesioMeloJunior @axaysagathiya

### CODE REVIEW

**Review by EclesioMeloJunior — APPROVED** [review]

**Review by jimjbrettj — DISMISSED** [review]

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]
While trying to run Gossamer I get the following error, looks like `paseo-bootnode.radiumblock.com` is encoded differently or is not correct
```
 failed to parse multiaddr 
"/dns/paseo-bootnode.radiumblock.com/tcp/30335/wss/p2p/12D3KooWeayZC8zag4Qrb4GosSn65MmfVZztRPMaBdgZnQqXRo": 

invalid value "12D3KooWeayZC8zag4Qrb4GosSn65MmfVZztRPMaBdgZnQqXRo" for protocol p2p: failed to parse p2p addr: 12D3KooWeayZC8zag4Qrb4GosSn65MmfVZztRPMaBdgZnQqXRo multihash length inconsistent: expected 2; got 4
```

**Comment by q9f** [comment]
I took it from the upstream PR here: https://github.com/paseo-network/runtimes/pull/12

How can I double check the issue is upstream and not our implementation?

**Comment by EclesioMeloJunior** [comment]
> I took it from the upstream PR here: [paseo-network/runtimes#12](https://github.com/paseo-network/runtimes/pull/12)
> 
> How can I double check the issue is upstream and not our implementation?

We use https://github.com/multiformats/go-multiaddr to parse these p2p addresses, so I think we should investigate its implementation, the parse is done at `dot/network/utils.go` in the function `stringToAddrInfo`

**Comment by q9f** [comment]
I removed the bootnode for now, will investigate the hash in another step.

**Review by EclesioMeloJunior — APPROVED** [review]

**Pull request merged**
