### PR TITLE
Disable Send/Ping tests

### PR DESCRIPTION
**Pull request by noot**
TEST PR, trying to figure out what the issue with travis is

## Changes
- turned off nat port mapping

## Tests:
```
go test ./p2p/...
```

### CODE REVIEW

**Comment by noot** [comment]
@ansermino no more NAT errors, but get this instead:
```
Error: response from https://api.codeclimate.com/v1/test_reports.
HTTP 401: You are not authorized for this action
```
something wrong with codeclimate?

**Comment by dutterbutter** [comment]
> @ansermino no more NAT errors, but get this instead:
> 
> ```
> Error: response from https://api.codeclimate.com/v1/test_reports.
> HTTP 401: You are not authorized for this action
> ```
> something wrong with codeclimate?

I believe our code climate secret might need updating?

**Comment by ansermino** [comment]
Opened a support issue with Travis, will update

**Comment by noot** [comment]
@ansermino travis passed!!! yay

**Pull request merged**
