### PR TITLE
fix node restart bug

### LINKED ISSUE #1152: Error trying to restart node: failed to retrieve :code from trie: trie with given root does not exist:
## Expected Behavior

- Should be able to restart node that was previously stopped without error.

## Current Behavior

- Sometimes node will give error when trying to start a node that was stopped. 
```
INFO[10-28|15:52:48] initializing node services...            pkg=dot name=gssmr id=gssmr basepath=/home/emack/.gossamer/alice_test caller=node.go:222
INFO[10-28|15:52:48] creating state service...                pkg=dot caller=services.go:47
EROR[10-28|15:52:48] failed to create node services           pkg=cmd error="failed to retrieve :code from trie: trie with given root does not exist: 0x304c0ae83b66ac958ca62255ebbcc79f92d41abd0cabe96784785c9399c83f04" caller=main.go:205
failed to retrieve :code from trie: trie with given root does not exist: 0x304c0ae83b66ac958ca62255ebbcc79f92d41abd0cabe96784785c9399c83f04

```

## Possible Solution

- 

## Steps to Reproduce

1. Init node (Using genesis_oneauth.json config) and start
2. Stop node
3. Try starting again, you may get this error.  I have not found a pattern to re-create the error every time.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

### PR DESCRIPTION
**Pull request by noot**
## Changes

- update `state.StoreLatestStorageHash` to store root directly
- flush db before closing

## Tests

set config `babe-threshold = "max"`
```
make gossamer
 ./bin/gossamer --key alice init --force 
./bin/gossamer --key alice --config chain/gssmr/config.toml --log debug
```
ctrl+c to stop the node after a couple seconds, rerun last command, repeat until you are conviced there are no more restart issues

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [x] All integration tests and required coverage checks are passing

## Issues

- related to #1152

### CODE REVIEW

**Review by RyRy79261 — APPROVED** [review]
Ran locally a couple times, couldn't get it to crash, looks good to me

**Review by arijitAD — APPROVED** [review]
Good catch.

**Comment by edwardmack** [comment]
Unfortunately it still crashes for me (after running a while).  I'm letting in run until I see this error is the logs 
```
 DBUG[11-25|17:58:28] [ext_print_utf8]                         pkg=runtime module=go-wasmer message="panicked at 'storage is not null, therefore must be a valid type: Error', /home/elizabeth/noot/substrate/srml/support/src/storage/unhashed.rs:25:9" caller=legacy_imports.go:142
EROR[11-25|17:58:28] block authoring                          pkg=babe error="Failed to call the `Core_initialize_block` exported function." caller=babe.go:520
```

When I try re-starting after I've seen this, it fails with:
```
INFO[11-25|18:00:18] initializing node services...            pkg=dot name=gssmr id=gssmr basepath=/home/emack/.gossamer/alice_test caller=node.go:222
INFO[11-25|18:00:18] creating state service...                pkg=dot caller=services.go:48
EROR[11-25|18:00:18] failed to create node services           pkg=cmd error="failed to create state service: failed to start state service: failed to get load storage trie from database: Key not found" caller=main.go:205
failed to create state service: failed to start state service: failed to get load storage trie from database: Key not found

```

I don't know what's causing the Failed to call Core_initialize_block error.  I'm running with toml config:
```
[global]
name = "gssmr"
id = "gssmr"
basepath = "~/.gossamer/alice_test"
log = "info"

[log]
core = ""
network = ""
rpc = "info"
state = ""
runtime = "debug"
babe = ""
grandpa = ""

[init]
genesis-raw = "/home/emack/.gossamer_test/genesis_oneauth.json"
#genesis-raw = "./chain/gssmr/genesis-raw.json"

[account]
key = ""
unlock = ""

[core]
roles = 4
babe-authority = true
grandpa-authority = true
babe-threshold = "max"
slot-duration = 1500

[network]
port = 7001
bootnodes = []
protocol = "/gossamer/gssmr/0"
nobootstrap = false
nomdns = false

[rpc]
enabled = true
port = 8545
host = "localhost"
modules = ["system", "author", "chain", "state", "dev", "rpc"]
ws-port = 8546
ws-enabled = true

```
using genesis_oneauth.json so that I can test finalization.

**Comment by noot** [comment]
@edwardmack I'll take another look at it!

**Comment by noot** [comment]
@edwardmack  I made some updated to how the TrieState was being used, it wasn't being properly copied before block building. could you try again?

**Pull request merged**
