### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by vtjl10**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected "Minor changes changes" to "Minor changes".
Corrected "piplelines" to "pipelines".
Corrected "gossmer" to "gossamer".
Corrected "Sate" to "State".

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Review by EclesioMeloJunior — APPROVED** [review]
thks for your contribution!

**Comment by vtjl10** [comment]
@EclesioMeloJunior Do I need to make any additional changes before merging?

**Comment by dimartiro** [comment]
@vtjl10 thanks for fixing this typos! 
Could you please rebase your branch, it is out-of-date with our develop.
After that we will be able to merge ❤️

**Review by haikoschol — APPROVED** [review]
tyvm @vtjl10!

**Pull request merged**
