### PR TITLE
script to test polkadot.js/api functions

### PR DESCRIPTION
**Pull request by edwardmack**
## Changes

- This adds Node.js javascript test script for testing polkadot.js/api.  It calls polkadot.js/api functions and displays output to console.
-
-

## Tests

Install polkadot.js/api package (assuming you already have node.js and npm installed).
```
cd tests/polkadotjs_test/
npm install
```
Start building blocks with gossamer node.  Then run script (from within tests/polkadotjs_test/).
```
node test.js
```
Observe the console output for results or errors.

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [ ] All integration tests and required coverage checks are passing

## Issues

- closes: #1198

### CODE REVIEW

**Review by RyRy79261 — APPROVED** [review]
This is great, could use the code to create a dashboard later on

**Review by noot — APPROVED** [review]
great stuff! @dutterbutter can we get this added to CI somehow?

**Review by anthdm — APPROVED** [review]

**Review by arijitAD — APPROVED** [review]

**Comment by dutterbutter** [comment]
> great stuff! @dutterbutter can we get this added to CI somehow?

@noot absolutely! Will be added with #1228

**Comment by arijitAD** [comment]
Screenshot 2021-01-27 at 9 58 41 PM
I ran this against the substrate node. It errors out. Can you check this?

**Pull request merged**
