### PR TITLE
cmd, core, consensus/babe: add configs for core.Service, babe.Session, add keystore

### PR DESCRIPTION
**Pull request by noot**
## Changes
- cleanup core and babe a bit, have their constructors take a config struct instead of a bunch of params. will make it easier to update config options in the future, rather than having to update function args everywhere
- add keystore to core/babe
- replace babe key stubs with key types

## Tests:
```
go test ./...
```

### CODE REVIEW

**Comment by noot** [comment]
is there any way to ignore the structcheck in the linter? the struct fields are actually used (babe/runtime.go config decoding uses them) it's just not direct

**Comment by ansermino** [comment]
> is there any way to ignore the structcheck in the linter? the struct fields are actually used (babe/runtime.go config decoding uses them) it's just not direct

They will be ignored when decoding, thus are unused.

**Comment by noot** [comment]
@ansermino  I thought structs within structs was ok for decoding :thinking_face: slightly confused

**Comment by ansermino** [comment]
@noot unexpoted fields are always ignored. A package cannot access unexported fields of a struct defined in another package. As such, `codec` can never operate on unexported fields, encoding or decoding.

**Comment by noot** [comment]
@ansermino true, I forgot about the fields inside AuthorityDataRaw. I have updated them to be exported, since they should be decoded from the config

**Pull request merged**
