### PR TITLE
Node optimization 

### PR DESCRIPTION
**Pull request by anthdm**
## Changes

Added this PR for discussions and finding when profiling Gossamer binary. Branched of noot `handle-body` branch for syncing purposes.

- 
-
-

## Tests

```

```

## Checklist

- [ ] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [ ] I have provided as much information as possible and necessary
- [ ] I have reviewed my own pull request before requesting a review
- [ ] All integration tests and required coverage checks are passing

## Issues

- related to #1326

### CODE REVIEW

**Comment by anthdm** [comment]
Goroutines @ 40 blocks synced 

```
goroutine profile: total 510
94 @ 0x5c49c5 0x5d4985 0xac2594 0x5fa941
#	0xac2593	github.com/dgraph-io/badger/v2/y.(*WaterMark).process+0x2d3	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/y/watermark.go:212

92 @ 0x5c49c5 0x5d4985 0xaf6bcf 0x5fa941
#	0xaf6bce	github.com/dgraph-io/badger/v2.(*levelsController).runCompactor+0x2ae	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/levels.go:390

47 @ 0x5c49c5 0x5d4985 0xae6635 0x5fa941
#	0xae6634	github.com/dgraph-io/badger/v2.(*DB).updateSize+0x154	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:1200

46 @ 0x5c49c5 0x5912a5 0x590eeb 0xb1b765 0x5fa941
#	0xb1b764	github.com/dgraph-io/badger/v2.(*valueLog).waitOnGC+0x64	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1851

46 @ 0x5c49c5 0x5912a5 0x590f2b 0xae5f57 0xb1e357 0x5fa941
#	0xae5f56	github.com/dgraph-io/badger/v2.(*DB).flushMemtable+0xb6	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:1107
#	0xb1e356	github.com/dgraph-io/badger/v2.Open.func5+0x36		/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:377

46 @ 0x5c49c5 0x5d4985 0xae40f7 0x5fa941
#	0xae40f6	github.com/dgraph-io/badger/v2.(*DB).doWrites+0x416	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:862

46 @ 0x5c49c5 0x5d4985 0xb04588 0x5fa941
#	0xb04587	github.com/dgraph-io/badger/v2.(*publisher).listenForUpdates+0x167	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/publisher.go:67

46 @ 0x5c49c5 0x5d4985 0xb1befd 0x5fa941
#	0xb1befc	github.com/dgraph-io/badger/v2.(*valueLog).flushDiscardStats+0x17c	/home/anthdm/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1948

5 @ 0x5c49c5 0x5d4985 0xdd287a 0x5fa941
#	0xdd2879	github.com/jbenet/goprocess/context.CloseAfterContext.func1+0xd9	/home/anthdm/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/context/context.go:65

2 @ 0x5c49c5 0x5bd2db 0x5f4ad5 0x6612e5 0x662865 0x662844 0x6f475b 0x71703c 0x714f9d 0xf158de 0x5fa941
#	0x5f4ad4	internal/poll.runtime_pollWait+0x54			/usr/local/go/src/runtime/netpoll.go:220
#	0x6612e4	internal/poll.(*pollDesc).wait+0x44			/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x662864	internal/poll.(*pollDesc).waitRead+0x1c4		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#	0x662843	internal/poll.(*FD).ReadFrom+0x1a3			/usr/local/go/src/internal/poll/fd_unix.go:215
#	0x6f475a	net.(*netFD).readFrom+0x5a				/usr/local/go/src/net/fd_posix.go:61
#	0x71703b	net.(*UDPConn).readFrom+0x5b				/usr/local/go/src/net/udpsock_posix.go:47
#	0x714f9c	net.(*UDPConn).ReadFrom+0x5c				/usr/local/go/src/net/udpsock.go:118
#	0xf158dd	github.com/whyrusleeping/mdns.(*Server).recv+0x9d	/home/anthdm/go/pkg/mod/github.com/whyrusleeping/mdns@v0.0.0-20190826153040-b9b60ed33aa9/server.go:116

2 @ 0x5c49c5 0x5d4985 0xe3f291 0xc4d9fc 0x5fa941
#	0xe3f290	github.com/libp2p/go-libp2p-kad-dht/providers.(*ProviderManager).run+0x2d0	/home/anthdm/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.8.3/providers/providers_manager.go:134
#	0xc4d9fb	github.com/jbenet/goprocess.(*process).Go.func1+0x3b				/home/anthdm/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134

2 @ 0x5c49c5 0x5d4985 0xe4a0c8 0x5fa941
#	0xe4a0c7	github.com/libp2p/go-libp2p-kad-dht/rtrefresh.(*RtRefreshManager).loop+0x507	/home/anthdm/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.8.3/rtrefresh/rt_refresh_manager.go:138

2 @ 0x5c49c5 0x5d4985 0xe5565e 0xc4d9fc 0x5fa941
#	0xe5565d	github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).fixLowPeersRoutine+0x17d	/home/anthdm/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.8.3/dht.go:382
#	0xc4d9fb	github.com/jbenet/goprocess.(*process).Go.func1+0x3b			/home/anthdm/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134

2 @ 0x5c49c5 0x5d4985 0xe55c25 0x5fa941
#	0xe55c24	github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).persistRTPeersInPeerStore+0x144	/home/anthdm/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.8.3/dht.go:454
```

**Comment by anthdm** [comment]
Also, CPU profile shows the massive amount of time spent in `runtime.Futex` which is basically a Linux system call that handles locking. Almost all of those calls origin from `Badger` code, hence lots of optimization needs to be done on how we handle our DB writes and reads.

**Review by RyRy79261 — APPROVED** [review]

**Comment by anthdm** [comment]
After a deeper dive, it's pretty clear we have some kind of memory leak coming from the following routines:

- `github.com/dgraph-io/badger/v2/y.(*WaterMark).process+0x2d3`
- `github.com/dgraph-io/badger/v2.(*levelsController).runCompactor+0x2ae`
- `github.com/dgraph-io/badger/v2.(*valueLog).waitOnGC+0x64`
- and a couple more all coming from badger.

Each block we process opens up 2 of the following routines:
- `github.com/dgraph-io/badger/v2/y.(*WaterMark).process+0x2d3`
- `github.com/dgraph-io/badger/v2.(*levelsController).runCompactor+0x2ae`

And 1 routine for all the other badger logic but they are never closed, hence freaking out the scheduler.

Running all created databases with the option `InMemory` set to true does not resolve this problem.

flame

**Comment by noot** [comment]
@anthdm do you have any information on the memory usage of the node?

**Comment by noot** [comment]
closing for now

**Pull request closed without merging**
