### PR TITLE
chore(lib/trie): add Trie `DeepCopy` unit test

### PR DESCRIPTION
**Pull request by qdm12**
## Changes

- Simple test addition for DeepCopy to reach full test coverage on trie.go

I often check for 'red' code paths in this file to make sure I cover everything since it's a rather complex source file. And that's the only red path showing up, and I wanted it gone since I would check it every time.

## Tests

```
go test ./lib/trie/...
```

### CODE REVIEW

**Review by noot — APPROVED** [review]

**Review by kishansagathiya — CHANGES_REQUESTED** [review]
The code looks good, but I am not sure why we need to check for mutations!

Why can't we just compare two structs (old struct and new one after copy) and its properties by reference?https://go.dev/play/p/zbmQpUbIEXp

**Review by timwu20 — APPROVED** [review]

**Comment by qdm12** [comment]
> The code looks good, but I am not sure why we need to check for mutations!
> 
> Why can't we just compare two structs (old struct and new one after copy) and its properties by reference?https://go.dev/play/p/zbmQpUbIEXp

That works if fields are not pointers/slices but otherwise we should *ideally* check for mutation for pointer/slices fields. Even if the root element is copied, we want to check everything is deep copied including fields of the struct. So check for pointer fields, interfaces, maps and slices fields.

**Review by kishansagathiya — APPROVED** [review]
> That works if fields are not pointers/slices but otherwise we should ideally check for mutation for pointer/slices fields. Even if the root element is copied, we want to check everything is deep copied including fields of the struct. So check for pointer fields, interfaces, maps and slices fields.

I think all that should be possible. 
- You can compare generation with `&`
- You can compare root directly since it is going to be pointer mostly
- You can run a loop through childTries and compare tries using recursion of this whole trie-compare function.
- You can run a loop through deletedKeys and compare values using `&`

but, I will leave that upto you!

**Comment by qdm12** [comment]
@kishansagathiya good suggestion, done 👍

I went a bit overboard and wrote [some helper functions to get the pointer of anything](https://github.com/ChainSafe/gossamer/blob/518a15ec030bcce2cb02308ae15f2520fd19e36b/lib/trie/trie_test.go#L177-L217) and code looks much cleaner now. All this `reflect` just made me realize I wrote https://github.com/qdm12/reprint which I could had used here 😄 but anyway too late

**Pull request merged**
