### PR TITLE
fix(.github): disable fail fast for integration tests

### PR DESCRIPTION
**Pull request by timwu20**
## Changes

- disables fail-fast for the integration tests workflow
- ensures that all packages in the matrix are tested and not cancelled if one fails

## Tests

- can be seen on this PR

### CODE REVIEW

**Comment by dimartiro** [comment]
I understand that this is to improve the dev experience, but the tradeoff is that it will consume more github credits right?

**Review by edwardmack — APPROVED** [review]
Nice change.

**Review by jimjbrettj — APPROVED** [review]
good call, thanks for this

**Comment by timwu20** [comment]
> I understand that this is to improve the dev experience, but the tradeoff is that it will consume more github credits right?

We use buildjet for our github runners, and I believe we pay monthly.

**Review by dimartiro — APPROVED** [review]
> We use buildjet for our github runners, and I believe we pay monthly.

Ok that was my only concern, approved!

**Pull request merged**
