### PR TITLE
adds github actions ci

### PR DESCRIPTION
**Pull request by dutterbutter**
## Changes

This does not remove `travis.yml` from the repo, once this lands I will make a subsequent PR for its removal to ensure the CI is working as expected. Some `stress_tests` continue to be inconsistent largely due to connection refused issues. Nonetheless with actions we are able to run far more concurrent jobs and the tests now run concurrently and should only take a max ~15 minutes. Travis only allows for a very limited number of concurrent jobs hence why our builds were sometimes taking much longer. 

They're some improvements that can be made, such as improved docker caching. Lastly, the `vet-check` is commented out until #1243 lands. 

- Add github actions ci
- Skip a pesky stress test (will need to revisit)
-

## Tests

```

```

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [ ] All integration tests and required coverage checks are passing

## Issues

-

### CODE REVIEW

**Comment by noot** [comment]
@dutterbutter is there a way to rerun only 1 action with github actions? right now i only see re-run all

otherwise looks good! being able to run the jobs concurrently will definitely help :D

**Comment by dutterbutter** [comment]
> @dutterbutter is there a way to rerun only 1 action with github actions? right now i only see re-run all
> 
> otherwise looks good! being able to run the jobs concurrently will definitely help :D

Currently you can only rerun 1 action but it looks to be out their roadmap!

**Comment by noot** [comment]
@dutterbutter sorry so we can rerun just 1 action now? or just all? lol

**Comment by dutterbutter** [comment]
> @dutterbutter sorry so we can rerun just 1 action now? or just all? lol

Sorry, re-run all actions/jobs. You can not run specific jobs in isolation.

**Review by RyRy79261 — APPROVED** [review]

**Review by arijitAD — APPROVED** [review]
All tasks are completed in under 10 mins. Pretty Awesome!

**Review by noot — APPROVED** [review]

**Comment by dutterbutter** [comment]
For some reason Code Climate does not want to play nice with actions :( but I have submitted a support ticket with code climate so hopefully we hear back and can resolve the issue. Here is the example I was working off: 

https://docs.codeclimate.com/docs/github-actions-test-coverage

**Pull request merged**
