### PR TITLE
chore(ci): simplify Docker setup

### PR DESCRIPTION
**Pull request by qdm12**
## Changes

- Use built-in `DOCKER_BUILDKIT=1`
- Remove QEMU setup (no emulation)
- Remove Buildx setup (no emulation)
- Remove default values: `file: ./Dockerfile`, `platforms: linux/amd64`, `push: false`
- Remove unneeded `name` and `id` of Docker steps

## Tests

CI suite passing

## Primary Reviewer

@EclesioMeloJunior

### CODE REVIEW

**Review by EclesioMeloJunior — APPROVED** [review]
nit: could we keep the `file: ./Dockerfile` argument?

**Review by jimjbrettj — APPROVED** [review]
lgtm

**Comment by qdm12** [comment]
@EclesioMeloJunior 

> nit: could we keep the `file: ./Dockerfile` argument?

Why though? It's the default argument, I don't see the point keeping it :thinking:

**Comment by EclesioMeloJunior** [comment]
Yea, I know, just suggested to be more explicit. For example in the case of changing the docker file name so other ppl know where to change.

**Comment by qdm12** [comment]
> Yea, I know, just suggested to be more explicit. For example in the case of changing the docker file name so other ppl know where to change.

I get your point, although then you might end up with a hundred option fields set to their defaults. It's better to keep it to the minimum to reduce cognitive load :brain: 

Also we will likely never rename that `Dockerfile` to something else :smile:

**Pull request merged**
