### PR TITLE
docs(issue): user story issue template

### PR DESCRIPTION
**Pull request by qdm12**
## Changes

- User story issue yml template
  - Dropdown `As a`
  - Textarea `I want to`
  - Textarea `Because`

## Tests

- Not relevant

## Issues

- No issue

## Primary Reviewer

- @danforbes 

For the curious, [yml github issue template syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

### CODE REVIEW

**Review by EclesioMeloJunior — APPROVED** [review]

**Comment by danforbes** [comment]
Thanks for creating this, Quentin 🙏🏻 I'm not sure if I think that this template is necessary for now, but I will add some resources for us to refer to if we decide to prioritize this.

- [Mozilla Developer Network user story template](https://github.com/mdn/sprints/blob/master/.github/ISSUE_TEMPLATE/user-story-template.md)
- [AlphaFounders user story template](https://github.com/AlphaFounders/style-guide/blob/master/agile-user-story.md#template)

**Comment by qdm12** [comment]
@danforbes actually I wouldn't mind having an extra template option for user stories, so we can use them optionally (if we feel like it/like it applies).

**Review by danforbes — APPROVED** [review]

**Comment by danforbes** [comment]
@qdm12 - approved!

**Comment by qdm12** [comment]
Yayy :tada: We can always modify or remove it later if we feel like it!

**Pull request merged**
