### PR TITLE
chore(deps): Remove unneeded Go modules dependencies

### PR DESCRIPTION
**Pull request by qdm12**
## Changes

- Remove unneeded indirect Go modules dependencies
- Add note on pre-push git hook that indirect dependencies are not removed with `go mod tidy` only

## Issues

No issue, this was a trivial change without any prior issue/idea in mind.

## Tests

(Re-added to pass issue body CI check)

## Additional notes

This was done by removing all `// indirect` imports from `go.mod` then re-run `go mod tidy`, in order to only import required indirect dependencies. This was also run with `CGO_ENABLED=1` to ensure C related code is taken care of as well.

### CODE REVIEW

**Review by arijitAD — APPROVED** [review]

**Review by EclesioMeloJunior — APPROVED** [review]

**Comment by qdm12** [comment]
Note there is a [unit test panicing](https://github.com/ChainSafe/gossamer/pull/1809/checks?check_run_id=3721447909), although that's probably unrelated to the changes I think.

**Comment by qdm12** [comment]
> Note there is a [unit test panicing](https://github.com/ChainSafe/gossamer/pull/1809/checks?check_run_id=3721447909), although that's probably unrelated to the changes I think.

I digged a bit in the unit tests in `dot/rpc/subscription`. It turns out each unit test individually produces data races (checked with `go test -race ./dot/rpc/subscription`). That's most likely the cause of the flaky test producing a nil pointer panic occasionally. Is it expected to have data races in the tests in this package?

**Comment by timwu20** [comment]
> > Note there is a [unit test panicing](https://github.com/ChainSafe/gossamer/pull/1809/checks?check_run_id=3721447909), although that's probably unrelated to the changes I think.
> 
> I digged a bit in the unit tests in `dot/rpc/subscription`. It turns out each unit test individually produces data races (checked with `go test -race ./dot/rpc/subscription`). That's most likely the cause of the flaky test producing a nil pointer panic occasionally. Is it expected to have data races in the tests in this package?

Ideally we shouldn't have race conditions in the tests.

**Comment by timwu20** [comment]
Did you run `go mod tidy`? I see a lot of repeated lines in go.sum.

**Comment by qdm12** [comment]
> Ideally we shouldn't have race conditions in the tests.

Uh ok I'll look into it eventually.

> Did you run `go mod tidy`? I see a lot of repeated lines in go.sum.

Yes, that's how `go.sum` is, lots of repetition... Unless you delete it and re-run `go mod tidy`, but then it loses its purpose 😇 
Note there are less lines than before in `go.sum`.

**Comment by noot** [comment]
@qdm12 could you resolve the merge conflicts? will merge this right after!

**Comment by qdm12** [comment]
@noot done 👍

**Review by EclesioMeloJunior — APPROVED** [review]

**Pull request merged**
