### PR TITLE
Elizabeth/p2p broadcast

### LINKED ISSUE #57: Implement broadcast to all peers

### PR DESCRIPTION
**Pull request by noot**
## Changes
- implemented Broadcast which sends a message to all peers
- implemented Stop which stops the libp2p service

## Tests:
```
go test ./p2p/...
```

### Fixes:
Closes #57

### CODE REVIEW

**Comment by ansermino** [comment]
@noot lint that :hankey: !

**Comment by noot** [comment]
@ansermino tests fail due to same reason as send, since boradcast uses send. I will probably open an issue in libp2p for this, not sure what's going wrong

**Comment by dutterbutter** [comment]
@noot @ansermino running tests locally for this branch also fails.

```
--- FAIL: TestBroadcast (0.48s)
    p2p_test.go:227: Broadcast error: failed to broadcast: routing: not found
```

**Comment by noot** [comment]
@dutterbutter hm okay, it is definitely to do with environment but not sure exactly what is it.. maybe it makes a difference that david and i are on linux and you're on mac? either way needs to be fixed

**Comment by dutterbutter** [comment]
> @dutterbutter hm okay, it is definitely to do with environment but not sure exactly what is it.. maybe it makes a difference that david and i are on linux and you're on mac? either way needs to be fixed

I can try to investigate on my end and see what I can find

**Comment by ansermino** [comment]
Fails locally for me as well. 

Fyi -- I usually don't make any attempt to review unless travis passes.

**Comment by ansermino** [comment]
@noot just a reminder to clear your cache (`go clean -testcache`)

**Comment by ansermino** [comment]
Blocked by #92

**Pull request closed without merging**
