### PR TITLE
Elizabeth/scale fixed width ints

### PR DESCRIPTION
**Pull request by noot**
## Changes
Implemented encoding and decoding for fixed width ints ie. ints < 32 bits. If type for encoding is int8, int16. or int32, represent the integer as a little endian byte array. For decoding, we similarly read the int as a little endian byte array

## Tests:
```
go test ./codec/...
```

### CODE REVIEW

**Comment by ansermino** [comment]
Need to also allow choice of compact encoding uint8, uin16, etc. We should probably clarify what the intended use for fixed-width is before proceeding, we need some way to indicate which encoding we want.

Would suggest marking as draft until we have more info.

**Comment by noot** [comment]
@ansermino sounds good, yeah definitely need further info. in terms of uint8, uint16 etc. I think the int8, int16 cases would satisfy them, but can you confirm @dutterbutter

**Comment by dutterbutter** [comment]
> @ansermino sounds good, yeah definitely need further info. in terms of uint8, uint16 etc. I think the int8, int16 cases would satisfy them, but can you confirm @dutterbutter

I actually do not think it satisfies them, I believe you explicitly have to create a case for uints

**Comment by dutterbutter** [comment]
Can we close this PR and open it maybe as a DRAFT pr? I know it makes no difference however it's just nicer to look at as a Draft rather than a pending PR.

**Pull request closed without merging**
